language: python

cache: pip

sudo: required

dist: trusty

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev
  - pip install numpy==1.13.1

install:
  - pip install -e .

script:
  - python setup.py test

warnings_are_errors: true

notifications:
  email: false