language: python

cache: pip

sudo: required

dist: trusty

python:
  - "2.7"

before_install:
  - pip install -U pip
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev gdal-bin libgdal-dev
  - # Intall more recent versions of lib-proj, required by cartopy and only available on ubuntu repos post 16.04
  - wget http://mx.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
  - sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
  - wget http://mx.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
  - sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb
  - pip install numpy==1.13.1

install:
  - pip install -e .

script:
  - python setup.py test

warnings_are_errors: true

notifications:
  email: false